# Generated by Django 3.2.5 on 2021-07-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptomes',
            new_name='symptoms',
        ),
    ]
